{ pkgs, ... }: with pkgs; [
    brightnessctl
    chromium
    comic-mono-font
    ddcutil
    discord
    emojione
    font-awesome_5
    gajim
    gimp-with-plugins
    grim
    hack-font
    imv
    keepassxc
    lagrange
    libnotify
    networkmanager_dmenu
    obsidian
    obs-studio
    pamixer
    pavucontrol
    playerctl
    rofi
    sct
    signal-desktop
    slurp
    speedcrunch
    spotify
    swayidle
    thunderbird
    tris-upload-utils
    vlc
    volumeicon
    vscode
    wdisplays
    wl-clipboard
    xdg-desktop-portal-wlr
    zathura
    zoom-us
]
