#!/usr/bin/env python3
import functools
import json
import os
import shlex
import re
import subprocess
import sys
from typing import List

PATH = os.path.expanduser("~/.clipboard")


def run(s: str, inp: str = None) -> str:
    return subprocess.check_output(shlex.split(s), text=True, input=inp)


def notify(subj, message=""):
    subprocess.run(["notify-send", subj, message])


def read() -> List[str]:
    with open(PATH) as f:
        return json.load(f)


def write(xs: List[str]):
    with open(PATH, "w") as f:
        json.dump(xs, f)


def copy():
    xs = read()
    xs.insert(0, run("wl-paste").rstrip("\n"))
    write(xs)

    notify(f"clippy: copied ({len(xs)} active)", menuval(xs[0]))


def pop(n: int):
    xs = read()
    x = xs.pop(n)
    run("wl-copy", inp=x)
    write(xs)

    notify(f"clippy: popped ({len(xs)} active)", menuval(x))


def popfirstout():
    xs = read()
    x = xs.pop(0)
    write(xs)

    print(x)


def dump():
    xs = read()
    print("\n".join(xs))


def split():
    xs = read()
    x = xs.pop()
    xs.extend((r := re.split(r"[\t\n]", x)))
    write(xs)

    notify(f"clippy: split into {len(r)} pieces")


def clear():
    write([])

    notify("clippy: cleared")


def pop0():
    pop(0)


def paste(n: int):
    xs = read()
    run("wl-copy", inp=xs[n])

    notify(f"clippy: pasted", menuval(xs[n]))


def send(to: str):
    run(f"mosquitto_pub -h {to} -q 2 -s -t clippy", inp=run("wl-paste").rstrip("\n"))


def recv():
    run("wl-copy", inp=run("mosquitto_sub -t clippy -C 1").rstrip("\n"))


def rotate():
    xs = read()
    write(xs[1:] + xs[0])

    notify("clippy: rotated", menuval(read()[0]))


def menuval(x):
    x = x.replace("\n", " ")

    if len(x) > 83:
        x = x[:40] + "..." + x[-40:]

    return x


def dmenu(ispop=False):
    entries = read()
    if not entries:
        notify("clippy: nothing in buffer!")
        return

    ilist = [f"{idx:3}   {menuval(val)}" for idx, val in enumerate(entries)]

    ilist.append("!clear")
    ilist.append("!paste" if ispop else "!pop")

    inp = "\n".join(ilist)

    prompt = "pop" if ispop else "paste"
    result = run(f"rofi -dmenu -p {prompt}", inp=inp)

    result = result.split()
    if result[0].startswith("!"):
        {
            "!clear": clear,
            "!pop": functools.partial(dmenu, ispop=True),
            "!paste": dmenu,
            "!split": split,
        }[result[0]]()
    else:
        [paste, pop][ispop](int(result[0]))


def main():
    {
        "copy": copy,
        "pop": pop,
        "dmenu": dmenu,
        "clear": clear,
        "split": split,
        "popfirstout": popfirstout,
        "dump": dump,
    }[sys.argv[1]]()


if __name__ == "__main__":
    main()


# vim: ft=python
