#!/usr/bin/env bash

mkdir -p ~/.terms
find ~/.terms -perm 600 -delete

if [[ $1 = new ]]; then
    export DTACH_SOCK_PATH=$HOME/.terms/auto-`date +%Y-%m-%dT%H-%M-%S`
    alacritty -e dtach -c $DTACH_SOCK_PATH zsh --login
elif [[ $1 = ls ]]; then
    ls ~/.terms
elif [[ $1 = at ]]; then
    dtach -a ~/.terms/$2
elif [[ $1 = rename ]]; then
    mv $DTACH_SOCK_PATH ~/.terms/$2
fi
